use_local_files: false    # true - zamówienia brane są z plików a nie z Woo Commerce
use_local_printer: false  # true - drukuj paragony na ekranie zamiast na drukarce
local_files_path: './'
printer:
  port: 1
  speed: 9600
  timeout: 5
use_proxy: 0
proxy:
  http: 'http://10.158.100.1:8080'
  https: 'http://10.158.100.1:8080'