block_cipher = None

a = Analysis(['orders_receiver.py', 'receipt.py', 'version.py'],
             pathex=['${{ github.workspace }}'],
             binaries=[],
             datas=[],
             hiddenimports=['requests'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='orders_receiver_%VERSION%__built-%BUILD_DATE%__%BUILD_TIME%',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )