name: Build Figa Order Manager

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch current commit hash
      id: commithash
      run: |
        echo ::set-output name=hash::$(git rev-parse --short HEAD)

    - name: Set APP Name
      id: appname
      shell: bash
      run: |
        hash=${{ steps.commithash.outputs.hash }}
        datetime=$(date '+%m.%y__%H.%M')
        echo ::set-output name=appname::orders_receiver_#${{ github.run_number }}_$commithash_$datetime

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Run build script
      shell: cmd
      run: .\build.bat "${{ steps.appname.outputs.appname }}"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.appname.outputs.appname }}
        path: dist/*
