name: Build Figa Order Manager

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch current commit hash
      id: commithash
      run: |
        echo "hash=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

    - name: Set APP Name
      id: appname
      shell: bash
      run: |
        datetime=$(date '+%m.%y__%H.%M')
        echo "appname=orders_receiver_#${{ github.run_number }}_$hash_$datetime" >> "$GITHUB_ENV"

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Run build script
      shell: cmd
      run: .\build.bat "${{ env.appname }}"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.appname }}
        path: dist/*
